[package]
name = "advent2020"
version = "0.1.0"
authors = ["user <savovs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
claim = "0.4"